# Generated by Django 5.2.5 on 2025-08-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('bills', 'Bills'), ('health', 'Health'), ('other', 'Other')], max_length=50),
        ),
    ]
