# Generated by Django 5.2.5 on 2025-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapi', '0002_alter_expensemodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
